import starvote

ballots = [
    {
        "Full-body anime-style illustration": 5,
        "Aspect Ratio": 4,
        "A-pose suitable for 3D modeling": 5,
        "Young woman": 4,
        "Muted orange sleeveless hoodie": 5,
        "Loose hem": 3,
        "Fully extended parallel to ground": 5,
        "Elbows locked": 4,
        "Elegantly spread hands, distinct fingers": 5,
        "Cheerful, eyes closed, warm smile": 5,
        "Stylish bob, intricately detailed, flowing strands": 4,
        "Fashionable skirt, ends above the knee": 4,
        "Clearly visible": 5,
        "Straight, slightly apart": 4,
        "Deep black": 5,
        "Stark contrast with vibrant clothing": 5,
        "Wide framing, engaging illustration, ample arm space": 5,
    },
    {
        "Still life composition": 4,
        "Headless mannequin": 3,
        "Cozy off-shoulder cable knit aran sweater": 5,
        "Soft pastel blue color": 4,
        "Frilled skirt": 4,
        "Skirt falls gracefully above the knees": 5,
        "Warm pastel shades": 5,
        "Long sleeves extend past the wrists": 4,
        "Relaxed fit": 3,
        "Soft, layered frill design": 4,
        "Indoors": 5,
        "Soft overcast noon lighting": 4,
        "Natural, diffused glow": 4,
        "Background resembles warm and inviting cozy room": 5,
        "Gentle tones and youthful charm": 5,
        "Comfortable, inviting materials": 5,
        "Subtle props like plush cushions": 3,
        "Scattering of soft blankets": 4,
        "Intimate atmosphere": 5,
        "Elements of goth and Lolita fashion": 3,
        "Touch of cuteness": 4,
    },
    {
        "Full-body anime-style illustration": 5,
        "Young woman exuding confidence": 4,
        "Sleeveless functional mage outfit": 5,
        "Eyes closed": 4,
        "A-pose suitable for 3D modeling": 5,
        "Arms fully extended parallel to the ground": 5,
        "Elegantly spread hands with distinct fingers": 5,
        "Stylish sleeveless tunic": 4,
        "Adorned with intricate magical symbols": 5,
        "Made of lightweight enchanted fabric": 5,
        "Fitted shorts": 4,
        "Shorts accentuate her legs": 4,
        "Allows for agility": 5,
        "Expression conveys serenity and focus": 5,
        "Striking violet eyes softly closed": 4,
        "Moment of concentration or meditation": 4,
        "Long hair styled in a high ponytail": 1,
        "Dynamism in the pose": 5,
        "Sturdy leather sandals": 4,
        "Softly blurred mystical forest": 4,
        "Dappled sunlight": 5,
        "Ethereal glowing orbs": 4,
        "Enchanting atmosphere": 5,
        "Complements her mage persona": 4,
    },
    {
        "Full-body anime-style illustration": 5,
        "Adult fox girl": 4,
        "Standing confidently in a proper A-pose": 5,
        "Luxurious, bushy tail swaying playfully": 5,
        "Soft orange and white fur": 4,
        "Intricately designed garments": 5,
        "Flowing fabrics in rich earthy tones": 5,
        "Accented with delicate floral patterns": 4,
        "Collar adorned with charms": 4,
        "Loose and flared sleeves": 5,
        "Ethereal vibe": 5,
        "Large fox ears perked up": 5,
        "Striking amber eyes": 4,
        "Eyes sparkle with liveliness": 5,
        "Playful smile": 5,
        "Friendly expression": 5,
        "Long, wavy hair cascading down shoulders": 5,
        "Hair with highlights catching the light": 4,
        "Standing on grassy ground": 5,
        "Backdrop of a vibrant forest": 5,
        "Filled with trees and wildflowers": 4,
        "Composition ensures full figure display": 5,
        "Vibrant tail and expressive features on display": 5,
        "Harmonious balance with lush, green setting": 5,
        "Background slightly blurred": 4,
        "Colorful and inviting": 5,
    },
    {
        "Full-body anime-style illustration": 5,
        "Adult fox girl in a graceful A-pose": 5,
        "Large, perked-up fox ears": 5,
        "Long flowing hair styled in a high ponytail": 1,
        "Vibrant colors complementing enchanting mage persona": 5,
        "Expression conveys serenity and focus": 5,
        "Eyes closed": 4,
        "Muted orange sleeveless hoodie": 5,
        "Fashionable skirt that ends above the knee": 5,
        "Made of lightweight enchanted fabric": 5,
        "Intricate designs": 5,
        "Flowing fabrics in rich earthy tones": 5,
        "Stark contrast against vibrant clothing": 5,
        "Elegantly spreads hands": 5,
        "Displaying distinct fingers": 5,
        "Soft, natural glow enhances atmosphere": 5,
        "Lighting soft and diffused": 4,
        "Mimicking still life composition": 4,
        "Touch of cuteness": 5,
        "Capturing enchanting and colorful vibe": 5,
    },
    {
        "Full-body anime-style illustration": 5,
        "Adult fox girl in an A-pose": 5,
        "Large, perked-up fox ears": 5,
        "Long flowing hair styled in a high ponytail": 1,
        "Hair cascades beautifully": 4,
        "Vibrant character": 5,
        "Expression conveys serenity and focus": 5,
        "Eyes closed in a peaceful manner": 4,
        "Muted orange sleeveless hoodie": 5,
        "Fashionable skirt that ends above the knee": 5,
        "Crafted from lightweight enchanted fabric": 5,
        "Flows gracefully": 5,
        "Outfit features intricate designs": 5,
        "Rich earthy tones": 5,
        "Creates an ethereal vibe": 5,
        "Long sleeves extend past her wrists": 5,
        "Adds elegance": 5,
        "Soft, layered frill design": 5,
        "Introduces a touch of cuteness": 5,
        "Sturdy leather sandals": 5,
        "Overall appearance is colorful and inviting": 5,
        "Soft, diffused lighting": 5,
        "Enhances serene atmosphere": 5,
    },
    {
        "Full-body anime-style illustration": 5,
        "Adult fox girl in an A-pose": 5,
        "Large, perked-up fox ears": 5,
        "Long flowing hair styled in a high ponytail": 1,
        "Adds to her vibrant persona": 5,
        "Expression exudes serenity and focus": 5,
        "Eyes closed in a tranquil manner": 4,
        "Muted orange sleeveless hoodie": 5,
        "Paired with a fashionable skirt that ends above the knee": 5,
        "Designed from lightweight enchanted fabric": 5,
        "Flows gracefully": 5,
        "Emphasizes her ethereal vibe": 5,
        "Outfit showcases intricate designs": 5,
        "Rich earthy tones": 5,
        "Provides beautiful contrast": 5,
        "Layered frill design": 5,
        "Brings a touch of cuteness": 5,
        "Sturdy leather sandals": 5,
        "Grounds the overall aesthetic": 5,
        "Soft, diffused lighting bathes the scene": 5,
        "Enhances the colors and inviting atmosphere": 5,
        "Elegant pose highlights flowing fabrics": 5,
    },
    {
        "Aspect Ratio: 2:3": 5,
        "A full-body anime-style illustration": 5,
        "An adult fox girl in an A-pose suitable for 3D modeling": 5,
        "Large, perked-up fox ears": 5,
        "Long flowing hair styled in a high ponytail": 1,
        "Serenity and focus conveyed by her expression with eyes closed peacefully": 5,
        "Muted orange sleeveless hoodie that complements her look": 5,
        "Fashionable skirt that ends above the knee": 5,
        "Crafted from flowing fabrics in rich earthy tones": 5,
        "Outfit showcases intricate layers and soft frill designs": 5,
        "Touch of cuteness added to her appearance": 4,
        "Sturdy leather sandals grounding the overall aesthetic": 4,
        "Scene illuminated with soft, diffused lighting": 5,
        "Enhancing the serene atmosphere and highlighting the ethereal vibe": 5,
    },
]

results = starvote.allocated_score_voting(ballots, seats=15)

print(results)
